### ISSUE TITLE
gdb build error [ubuntu 24.10, python3.13, gcc-14]

### ISSUE THREAD

**Issue by jagiella** [ps3dev/ps3toolchain#128]
When build on ubuntu 24.10 with the most recent gcc-14 and python 3.13 installed I get the following gdb compiler error due to deprecated python-API-code usage:

```
In file included from ../../gdb/python/py-events.h:24,
                 from ../../gdb/python/py-evts.c:21:
../../gdb/python/python-internal.h: In function ‘void gdb_PySys_SetPath(const wchar_t*)’:
../../gdb/python/python-internal.h:279:3: error: ‘PySys_SetPath’ was not declared in this scope
  279 |   PySys_SetPath (const_cast<GDB_PYSYS_SETPATH_CHAR *> (path));
      |   ^~~~~~~~~~~~~
../../gdb/python/python-internal.h:279:3: note: the macro ‘PySys_SetPath’ had not yet been defined
../../gdb/python/python-internal.h:282:9: note: it was later defined here
  282 | #define PySys_SetPath gdb_PySys_SetPath
      |         ^~~~~~~~~~~~~
```

This function was deprecated since 3.11 and got removed in 3.13 from the python-C-API: 
https://docs.python.org/3/whatsnew/changelog.html#id136

So I guess, either the gdb patch should be updated or the gdb version should be bumped to a recent version.

**Comment by GWTRC** [comment]
Ditto on this issue. Been getting 20kb/s download speeds from ftp.gnu.org too (ran a speedtest and got 900mbps, issue's not on my end. probably.) so to sit there for 2 hours while all binutils, gcc, and gdb downloaded atrociously slow only for this to happen was rather frustrating. Glad I'm not the only one.

**Comment by crimsonblue17** [comment]
it also fails to compile for the same reason on void linux.
